# Generated by Django 5.2 on 2025-05-10 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('4XL', '4X Large'), ('5XL', '5X Large'), ('FREE', 'Free Size')], max_length=5)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='app.shirt')),
            ],
            options={
                'unique_together': {('shirt', 'size')},
            },
        ),
    ]
