# Generated by Django 5.2 on 2025-05-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shirtsizestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reduction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
